package com.devendra.shared.model;

public enum TargetAudience {
  TECH_ENTHUSIASTS,
  FITNESS_LOVERS,
  FASHIONISTAS,
  PARENTS,
  STUDENTS,
  PROFESSIONALS,
  GAMERS,
  TRAVELERS,
  FOODIES,
  BUSINESS_OWNERS,
  HEALTH_CONSCIOUS,
  LUXURY_SHOPPERS,
  BUDGET_SHOPPERS,
  PET_LOVERS,
  ENVIRONMENTALISTS
}
